package com.danco.training.controller.api;

public interface IHotelController {
	public void addGuest();
	public void deletGuest();
	public void sortByNameGuests();
	public void sortByDateGuests();
	public void showNumberOfGuests();
	public void showGuestsServicesSortedByCoast();
	public void showGuestsServicesSortedByDate();
	public void addServiceToGuest();
	public void printGuest();
	public void addRoom();
	public void deleteRoom();
	public void deleteGuestFromRoom();
	public void deleteAllGuestsFromRoom();
	public void changeRoomsCoast();
	public void changeRoomsStatusRepair();
	public void sortByCoastFreeRoom();
	public void sortByCopasityFreeRoom();
	public void sortByStarsFreeRoom();
	public void sortByCoastRoom();
	public void sortByCopasityRoom();
	public void sortByStarsRoom();
	public void showNumberOfFreeRooms();
	public void showChekOutDate();
	public void showRoomDetails();
	public void showPricePerRoom();
	public void showLastThreeGuests();
	public void addGuestInRoom();
	public void printRoom();
	public void addService();
	public void deleteService();
	public void changeServicesCoast();
	public void printService();
	public void cloneRoom();
	public void exportGuests();
	public void exportRooms();
	public void exportServices();
	public void importServices();
	public void importRooms();
	public void importGuests();
	public void buildServicesFromAnnot();
	public void buildGuestsFromAnnot();
	public void buildRoomsFromAnnot();
}
